### ISSUE TITLE
tab autocomplete issue

### ISSUE THREAD

**Issue by fiskmaas** [dosentmatter/rainbow-zsh-prompt#3]
Tab autocomplete indents and copies the input text. Have seen this issue before when editing .zshrc and have fixed it with adding '%' to various places where needed in the code. Though I'm not too familiar with scripting and coding so have no idea how to solve it in this case. Would love some input on this. 
![cpy2](https://user-images.githubusercontent.com/44087338/92476802-ceef1f00-f1df-11ea-9066-b926922a70e3.png)

**Comment by dosentmatter** [comment]
Hey @fiskmaas, I'm not really sure off the top of my head because I don't use zsh myself. I just ported it from [rainbow bash prompt](https://github.com/dosentmatter/rainbow-bash-prompt) after someone requested a zsh version.

If you are interested in fixing it, pull requests are welcome. If you don't understand parts of the code, feel free to ask. If you need some motivation on submitting a pull request, there is [hacktoberfest](https://hacktoberfest.digitalocean.com/) in October.
